--- 
settings_013: 
  created_on: 2007-04-09 16:30:36
  name: add_watermark_to_upper_right
  settings_count: 
  value_type: string
  updated_on: 2007-04-09 16:30:36
  lft: "24"
  id: "18"
  value: /home/bull/Rails/Workspace/benzine/trunk/public/images/auto55/logo_a55be_wallpaper_big.png
  rgt: "25"
  parent_id: "17"
settings_002: 
  created_on: 2007-04-03 17:47:02
  name: default
  settings_count: 
  value_type: string
  updated_on: 2007-04-03 17:47:02
  lft: "2"
  id: "6"
  value: small
  rgt: "3"
  parent_id: "5"
settings_014: 
  created_on: 2007-04-12 19:06:10
  name: small
  settings_count: 
  value_type: string
  updated_on: 2007-04-12 19:06:10
  lft: "19"
  id: "20"
  value: 150x94
  rgt: "20"
  parent_id: "12"
settings_003: 
  created_on: 2007-04-04 10:09:39
  name: versions
  settings_count: 
  value_type: string
  updated_on: 2007-04-04 10:09:39
  lft: "4"
  id: "7"
  value: ""
  rgt: "11"
  parent_id: "5"
settings_004: 
  created_on: 2007-04-04 10:09:50
  name: small
  settings_count: 
  value_type: string
  updated_on: 2007-04-04 10:09:50
  lft: "5"
  id: "8"
  value: ""
  rgt: "10"
  parent_id: "7"
settings_005: 
  created_on: 2007-04-04 10:10:04
  name: crop
  settings_count: 
  value_type: string
  updated_on: 2007-04-04 10:10:04
  lft: "6"
  id: "9"
  value: 150:94
  rgt: "7"
  parent_id: "8"
settings_006: 
  created_on: 2007-04-04 10:10:16
  name: size
  settings_count: 
  value_type: string
  updated_on: 2007-04-04 10:10:16
  lft: "8"
  id: "10"
  value: 150x94
  rgt: "9"
  parent_id: "8"
settings_007: 
  created_on: 2007-04-09 15:31:06
  name: ImageSettingsNew
  settings_count: 
  value_type: string
  updated_on: 2007-04-09 15:31:06
  lft: "15"
  id: "11"
  value: ""
  rgt: "28"
  parent_id: 
settings_008: 
  created_on: 2007-04-09 15:31:33
  name: versions
  settings_count: 
  value_type: string
  updated_on: 2007-04-09 15:31:33
  lft: "16"
  id: "12"
  value: ""
  rgt: "21"
  parent_id: "11"
settings_009: 
  created_on: 2007-04-09 16:00:35
  name: watermark_image
  settings_count: 
  value_type: string
  updated_on: 2007-04-09 16:00:35
  lft: "12"
  id: "14"
  value: /home/bull/Rails/Workspace/benzine/trunk/public/images/auto55/logo_a55be_wallpaper_big.png
  rgt: "13"
  parent_id: "5"
settings_010: 
  created_on: 2007-04-09 16:27:42
  name: normal
  settings_count: 
  value_type: string
  updated_on: 2007-04-09 16:27:42
  lft: "17"
  id: "15"
  value: 900>
  rgt: "18"
  parent_id: "12"
settings_011: 
  created_on: 2007-04-09 16:29:24
  name: transformations
  settings_count: 
  value_type: string
  updated_on: 2007-04-09 16:29:24
  lft: "22"
  id: "16"
  value: ""
  rgt: "27"
  parent_id: "11"
settings_012: 
  created_on: 2007-04-09 16:29:47
  name: normal
  settings_count: 
  value_type: string
  updated_on: 2007-04-09 16:29:47
  lft: "23"
  id: "17"
  value: ""
  rgt: "26"
  parent_id: "16"
settings_001: 
  created_on: 2007-04-03 17:46:37
  name: ImageSettings
  settings_count: 
  value_type: string
  updated_on: 2007-04-03 17:46:37
  lft: "1"
  id: "5"
  value: ""
  rgt: "14"
  parent_id: 
