--- 
settings_013: 
  created_on: 2007-07-11 14:28:13
  name: crop
  settings_count: 
  value_type: string
  updated_on: 2007-07-11 14:28:13
  lft: "20"
  id: "33"
  value: "100:30"
  rgt: "21"
  parent_id: "31"
settings_002: 
  created_on: 2007-04-03 17:47:02
  name: default
  settings_count: 
  value_type: string
  updated_on: 2007-04-03 17:47:02
  lft: "28"
  id: "6"
  value: cropped_and_watermarked
  rgt: "29"
  parent_id: "5"
settings_014: 
  created_on: 2007-07-11 14:28:33
  name: watermark_image
  settings_count: 
  value_type: string
  updated_on: 2007-07-11 14:28:33
  lft: "22"
  id: "34"
  value: /Users/ddfreyne/Desktop/sample_images/mask.gif
  rgt: "23"
  parent_id: "31"
settings_003: 
  created_on: 2007-04-04 10:09:39
  name: versions
  settings_count: 
  value_type: string
  updated_on: 2007-04-04 10:09:39
  lft: "2"
  id: "7"
  value: ""
  rgt: "27"
  parent_id: "5"
settings_015: 
  created_on: 2007-07-11 14:28:44
  name: watermark_position
  settings_count: 
  value_type: string
  updated_on: 2007-07-11 14:28:44
  lft: "24"
  id: "35"
  value: top_left
  rgt: "25"
  parent_id: "31"
settings_004: 
  created_on: 2007-04-04 10:09:50
  name: cropped
  settings_count: 
  value_type: string
  updated_on: 2007-04-04 10:09:50
  lft: "11"
  id: "8"
  value: ""
  rgt: "16"
  parent_id: "7"
settings_016: 
  created_on: 2007-07-11 14:29:02
  name: watermark_image
  settings_count: 
  value_type: string
  updated_on: 2007-07-11 14:29:02
  lft: "6"
  id: "36"
  value: /Users/ddfreyne/Desktop/sample_images/mask.gif
  rgt: "7"
  parent_id: "25"
settings_005: 
  created_on: 2007-04-04 10:10:04
  name: crop
  settings_count: 
  value_type: string
  updated_on: 2007-04-04 10:10:04
  lft: "14"
  id: "9"
  value: "50:50"
  rgt: "15"
  parent_id: "8"
settings_017: 
  created_on: 2007-07-11 14:29:15
  name: watermark_position
  settings_count: 
  value_type: string
  updated_on: 2007-07-11 14:29:15
  lft: "8"
  id: "37"
  value: top_left
  rgt: "9"
  parent_id: "25"
settings_006: 
  created_on: 2007-04-04 10:10:16
  name: size
  settings_count: 
  value_type: string
  updated_on: 2007-04-04 10:10:16
  lft: "12"
  id: "10"
  value: 300x300
  rgt: "13"
  parent_id: "8"
settings_018: 
  created_on: 2007-07-11 14:35:03
  name: processor
  settings_count: 
  value_type: string
  updated_on: 2007-07-11 14:35:03
  lft: "30"
  id: "38"
  value: rmagick
  rgt: "31"
  parent_id: "5"
settings_007: 
  created_on: 2007-05-15 16:31:31
  name: watermarked
  settings_count: 
  value_type: string
  updated_on: 2007-05-15 16:31:31
  lft: "3"
  id: "25"
  value: ""
  rgt: "10"
  parent_id: "7"
settings_019: 
  created_on: 2007-07-12 11:05:51
  name: default2
  settings_count: 
  value_type: string
  updated_on: 2007-07-12 11:05:51
  lft: "32"
  id: "39"
  value: cropped
  rgt: "33"
  parent_id: "5"
settings_008: 
  created_on: 2007-05-15 16:34:39
  name: size
  settings_count: 
  value_type: string
  updated_on: 2007-05-15 16:34:39
  lft: "4"
  id: "27"
  value: 500x500
  rgt: "5"
  parent_id: "25"
settings_009: 
  created_on: 2007-07-09 12:37:47
  name: address
  settings_count: 
  value_type: string
  updated_on: 2007-07-09 12:37:47
  lft: "36"
  id: "29"
  value: example_email_address@dotprojects.be
  rgt: "37"
  parent_id: "30"
settings_010: 
  created_on: 2007-07-09 12:54:38
  name: EmailSettings
  settings_count: 
  value_type: string
  updated_on: 2007-07-09 12:54:38
  lft: "35"
  id: "30"
  value: ""
  rgt: "38"
  parent_id: 
settings_011: 
  created_on: 2007-07-11 14:26:50
  name: cropped_and_watermarked
  settings_count: 
  value_type: string
  updated_on: 2007-07-11 14:26:50
  lft: "17"
  id: "31"
  value: ""
  rgt: "26"
  parent_id: "7"
settings_012: 
  created_on: 2007-07-11 14:27:09
  name: size
  settings_count: 
  value_type: string
  updated_on: 2007-07-11 14:27:09
  lft: "18"
  id: "32"
  value: 500x500
  rgt: "19"
  parent_id: "31"
settings_001: 
  created_on: 2007-04-03 17:46:37
  name: ImageSettings
  settings_count: 
  value_type: string
  updated_on: 2007-04-03 17:46:37
  lft: "1"
  id: "5"
  value: ""
  rgt: "34"
  parent_id: 
